/**
 * @module AuditTypes
 * Interface definitions for the audit trail service.
 */
import { type AuditLog } from "../schemas/audit.schema.js";

/**
 * Service for recording and retrieving system events.
 */
export interface AuditService {
  /** * Records a new event. 
   * 'id' and 'timestamp' are omitted as they are generated by the implementation.
   */
  log(data: Omit<AuditLog, 'id' | 'timestamp'>): Promise<void>;
  
  /** Retrieves the full list of recorded logs for administrative oversight. */
  getLogs(): Promise<AuditLog[]>;
}